### ISSUE TITLE
what is  'record Detection',it is an entity class?

### ISSUE THREAD

**Issue by Rivers-King** [jhgan00/java-ort-example-yolov5#10]
I'm very sorry as I have just started learning about onnx-related knowledge. I now need to use my own trained onnx model to recognize images. However, I encountered an issue while using your code. I believe 'Detection' should be a class, and that's also my idea
![image](https://github.com/jhgan00/java-ort-example-yolov5/assets/140472263/6af6b78a-da70-4f85-bd26-120c5274d45a)

**Comment by jhgan00** [comment]
The 'record' keyword was introduced in Java 14. Please check the version of Java you are using. Thank you.

**Comment by jhgan00** [comment]
```
public class Detection {
    private final String label;
    private final float[] bbox;
    private final float confidence;

    public Detection(String label, float[] bbox, float confidence) {
        this.label = label;
        this.bbox = bbox;
        this.confidence = confidence;
    }

    public String getLabel() {
        return label;
    }

    public float[] getBbox() {
        return bbox;
    }

    public float getConfidence() {
        return confidence;
    }
}
```

**Comment by Rivers-King** [comment]
ok,i see,thank you
