### ISSUE TITLE
ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by umi-soft** [jhgan00/java-ort-example-yolov5#5]
# Novice Question

Train with yolov8，option batch value 64，run your code has errors
```
OnnxTensor.createTensor ERROR

ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Got invalid dimensions for input: images for the following indices
 index: 0 Got: 1 Expected: 64
 Please fix either the inputs or the model.
```
if i set option batch value 16 and retrain，your code can run success。
I guess I need to make changes `NUM_INPUT_ELEMENTS` and `INPUT_SHAPE`，but I am clear about the specific meaning of the values and how to modify them.

**Comment by umi-soft** [comment]
The image size is also 640

**Comment by jhgan00** [comment]
Hello. Currently, my code is written without considering dynamic batch sizes. In other words, the code only works with a batch size of 1. Based on the error message, it seems that you exported the trained model to ONNX with a batch size of 64. If you could share the trained model or provide information about the input shape through apps like Netron, I would be able to assist you further.

<img width="1012" alt="스크린샷 2023-05-14 오후 12 30 08" src="https://github.com/jhgan00/java-ort-example-yolov5/assets/47095378/9a690bf0-35ea-48e5-9e31-831aecff609b">

**Comment by jhgan00** [comment]
- If you exported the trained model to ONNX with a batch size of 64, then during inference, you need to feed exactly 64 images to the model. 
- If you want to use a variable number of input images instead of a fixed number, you should export the model to ONNX with dynamic batch size support.

In both cases, we need to modify the current code

**Comment by umi-soft** [comment]
thanks, i get it.
